apiVersion: 1

deleteDatasources:
  - name: TimescaleDB
    orgId: 1
  - name: AppDatabase
    orgId: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: metrics_reader
    secureJsonData:
      password: '$METRICS_READER_PASS'
    jsonData:
      database: $METRICS_DB
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 10
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true

  - name: AppDatabase
    type: postgres
    url: database:5432
    user: data_reader
    secureJsonData:
      password: '$DATA_READER_PASS'
    jsonData:
      database: $POSTGRES_DB
      sslmode: 'disable'
      maxOpenConns: 5
      maxIdleConns: 5
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
